# Generated by Django 4.2.5 on 2024-02-05 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 13, 11, 9, 375381, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
